// Synced from Google Sheet "CBO List" / Sheet1 / Organization Name on 2026-05-29.
export const CBO_ORGANIZATIONS = [
  "360 academy",
  "826 National",
  "ABC",
  "Boys club of New York",
  "Breakthrough",
  "Carnegie Corporation of New York",
  "City of Refuge",
  "City Year",
  "Code.org",
  "College Bound Dorchester",
  "DonorsChoose",
  "Global Fund For Children",
  "Higher Education Recruitment Consortium",
  "International Paper Foundation",
  "KIPP Foundation",
  "National Center for Earth and Space Science Education",
  "National Education Association",
  "New Jersey seeds",
  "NYC Coalition for Educational Justice",
  "Oliver scholars",
  "Outside Lands Works (OLW)",
  "Prep 9 (Prep for Prep)",
  "Room to Read",
  "Scholarship America",
  "STEM Next",
  "Stepping Stone",
  "Talent Development Secondary (TDS)",
  "Teach For America",
  "The Education Trust",
  "The Mind Trust",
  "The NEA Foundation",
  "The Starfish Institute (100Kin10)",
  "Year Up",
]
