// Synced from Google Sheet "CBO List" / Sheet1 / Organization Name on 2026-05-29.
export const CBO_ORGANIZATIONS = [
  "ABC",
  "Prep 9 (Prep for Prep)",
  "DonorsChoose",
  "College Bound Dorchester",
  "826 National",
  "The NEA Foundation",
  "Code.org",
  "KIPP Foundation",
  "Teach For America",
  "STEM Next",
  "Room to Read",
  "Scholarship America",
  "National Education Association",
  "The Education Trust",
  "City Year",
  "Year Up",
  "The Mind Trust",
  "Talent Development Secondary (TDS)",
  "Higher Education Recruitment Consortium",
  "National Center for Earth and Space Science Education",
  "Outside Lands Works (OLW)",
  "The Starfish Institute (100Kin10)",
  "NYC Coalition for Educational Justice",
  "City of Refuge",
  "Carnegie Corporation of New York",
  "Global Fund For Children",
  "International Paper Foundation",
  "Oliver scholars",
  "New Jersey seeds",
  "360 academy",
  "Boys club of New York",
  "Stepping Stone",
  "Breakthrough",
]
