// Snapshot of accepting institutions from https://www.vericant.com/who-accepts/
// Last synced: 2026-08-21 from the public Who Accepts page
// (K-12 partners, junior boarding, summer programs, undergraduate/graduate).

export const VERICANT_ACCEPTING_INSTITUTIONS: string[] = [
  "All-Star Academy",
  "Asheville School",
  "Berkshire School",
  "Blair Academy",
  "Brooks School",
  "Canterbury School",
  "Chadwick School",
  "Concord Academy",
  "Church Farm School",
  "Cranbrook Schools",
  "Cushing Academy",
  "Elite Preparatory Academy",
  "Emma Willard School",
  "Episcopal High School",
  "George School",
  "Georgetown Preparatory School",
  "Ideaventions Academy",
  "John Bapst Memorial High School",
  "Kent School",
  "Kimball Union Academy",
  "Lakefield College School",
  "Lawrence Academy",
  "McCallie School",
  "Mercersburg Academy",
  "Middlesex School",
  "Miss Porter\u2019s School",
  "North Broward Preparatory School",
  "Peddie School",
  "Pickering College",
  "Pomfret School",
  "Ravenscroft School",
  "Ridley College",
  "Saint Andrew\u2019s School (FL)",
  "Saint James School",
  "San Domenico School",
  "Sandy Spring Friends School",
  "St. Andrew\u2019s School, DE",
  "St. Mark\u2019s School",
  "St. Stephen\u2019s Episcopal School TX",
  "Stevenson School",
  "Tabor Academy",
  "TASIS The American School in England",
  "The Cambridge School of Weston",
  "The Governor\u2019s Academy",
  "The Lawrenceville School",
  "The Loomis Chaffee School",
  "The Madeira School",
  "The Northwest School",
  "The Pennington School",
  "The Taft School",
  "The Webb Schools (CA)",
  "The Winchendon School",
  "Trinity-Pawling School",
  "Valley Forge Military Academy",
  "Virginia Episcopal School",
  "Western Reserve Academy (WRA)",
  "Westtown School",
  "Woodside Priory School",
  "Wyoming Seminary",
  "North Country School",
  "The Fessenden School",
  "Lawrenceville Summer Scholars",
  "Hotchkiss Summer Portals",
  "Choate Rosemary Hall Summer Programs",
  "Mercersburg Academy Summer Programs",
  "Loomis Chaffee Summer Programs",
  "Summer at St. Margaret\u2019s",
  "Cambridge School of Weston Summer",
  "Assumption University",
  "Babson College",
  "Bard College",
  "Barnard College",
  "Bates College",
  "Beloit College",
  "Bentley University",
  "Boston University",
  "Bowdoin College",
  "Brandeis University",
  "Bryn Mawr College",
  "Bucknell University",
  "California College of the Arts",
  "California Lutheran University",
  "Canadian Chinese School of Theology Vancouver",
  "Carleton College",
  "Carnegie Mellon University Heinz College of Information Systems, Public Policy, & Management",
  "Carnegie Mellon University",
  "Case Western Reserve University",
  "Chapman University Graduate School",
  "Claremont McKenna College",
  "Clark University",
  "Colby College",
  "College of the Holy Cross",
  "College of Wooster",
  "Colorado College",
  "Columbia University",
  "Cornell University",
  "Dartmouth College",
  "Davidson College",
  "Denison University",
  "DePauw University",
  "Dickinson College",
  "Drexel University Graduate School",
  "Drexel University",
  "Fordham University",
  "Franklin & Marshall College",
  "Furman University",
  "Georgia Institute of Technology",
  "Grinnell College",
  "Hamilton College",
  "Harvey Mudd College",
  "Haverford College",
  "Kenyon College",
  "Kyoto University International Undergraduate Program",
  "Lake Forest College",
  "Lawrence University",
  "Lehigh University",
  "Loyola Marymount University",
  "Macalester College",
  "Marquette University",
  "Michigan Technological University",
  "Middlebury College",
  "Mount Holyoke College",
  "National University of Singapore",
  "Northeastern University",
  "Oberlin College",
  "Occidental College Ohio",
  "Ohio Wesleyan University",
  "Pepperdine University",
  "Pomona College",
  "Reed College",
  "Rensselaer Polytechnic Institute",
  "Rhodes College",
  "Rice University",
  "Robert Morris University",
  "Salisbury University",
  "Santa Clara University",
  "Sarah Lawrence College",
  "Scripps College",
  "Skidmore College",
  "Smith College",
  "St. Olaf College",
  "Stanford University",
  "Swarthmore College",
  "Syracuse University",
  "The University of Tokyo Graduate School of Information Science and Technology",
  "Trinity College",
  "Tufts University",
  "Tulane University",
  "Union College",
  "University at Albany, SUNY",
  "University of Akron Graduate School",
  "University of California",
  "Merced Graduate School",
  "University of Denver",
  "University of Hartford",
  "University of Montana",
  "University of Notre Dame",
  "University of Oregon",
  "University of Puget Sound",
  "University of Richmond",
  "University of Southern California",
  "University of Vermont",
  "University of Virginia",
  "University of Washington",
  "Ursinus College",
  "Vassar College",
  "Villanova University",
  "Washington and Jefferson College",
  "Washington and Lee University",
  "Washington University in St. Louis",
  "Wesleyan University",
  "Wellesley College",
  "Westminster Theological Seminary",
  "Wheaton College (MA)",
  "Whitman College",
  "William & Mary",
  "Williams College",
  "Wofford College",
]
